# Labware
This example shows how to use the most important type in the `liquidhandling` package: `Labware`.

In [1]:
from robotools import liquidhandling

## Types of Labware
The `Labware` type describes well plates and troughs as 2-dimensional arrays. They have `min_volume` and `max_volume` to prevent you from pipetting unrealistic volumes.

Not only can `Labware` be used to create GWL-worklists in an object-oriented manner (see `Evotools_AssayPreparation`), it records its history of filling volumes. This is extremely useful if you're trying to create complex mixing/dilution procedures.

### Well plates
Well-plate-like labware is nothing more than a RxC grid of inidividual wells. Each has its own liquid volume.

In [2]:
plate = liquidhandling.Labware('24-well plate', rows=4, columns=6, 
    min_volume=100, max_volume=1000,
    initial_volumes=300
)
print(plate)

24-well plate
[[300. 300. 300. 300. 300. 300.]
 [300. 300. 300. 300. 300. 300.]
 [300. 300. 300. 300. 300. 300.]
 [300. 300. 300. 300. 300. 300.]]


The `Labware` has several useful properties. Most importantly: `wells` and `volumes`

In [3]:
plate.wells

array([['A01', 'A02', 'A03', 'A04', 'A05', 'A06'],
       ['B01', 'B02', 'B03', 'B04', 'B05', 'B06'],
       ['C01', 'C02', 'C03', 'C04', 'C05', 'C06'],
       ['D01', 'D02', 'D03', 'D04', 'D05', 'D06']], dtype='<U3')

In [4]:
plate.volumes

array([[300., 300., 300., 300., 300., 300.],
       [300., 300., 300., 300., 300., 300.],
       [300., 300., 300., 300., 300., 300.],
       [300., 300., 300., 300., 300., 300.]])

Well ids can be mapped to EVOware-style `positions` and numpy-style `indices`:

In [5]:
print(plate.positions)

{'A01': 1, 'A02': 5, 'A03': 9, 'A04': 13, 'A05': 17, 'A06': 21, 'B01': 2, 'B02': 6, 'B03': 10, 'B04': 14, 'B05': 18, 'B06': 22, 'C01': 3, 'C02': 7, 'C03': 11, 'C04': 15, 'C05': 19, 'C06': 23, 'D01': 4, 'D02': 8, 'D03': 12, 'D04': 16, 'D05': 20, 'D06': 24}


In [6]:
print(plate.indices)

{'A01': (0, 0), 'A02': (0, 1), 'A03': (0, 2), 'A04': (0, 3), 'A05': (0, 4), 'A06': (0, 5), 'B01': (1, 0), 'B02': (1, 1), 'B03': (1, 2), 'B04': (1, 3), 'B05': (1, 4), 'B06': (1, 5), 'C01': (2, 0), 'C02': (2, 1), 'C03': (2, 2), 'C04': (2, 3), 'C05': (2, 4), 'C06': (2, 5), 'D01': (3, 0), 'D02': (3, 1), 'D03': (3, 2), 'D04': (3, 3), 'D05': (3, 4), 'D06': (3, 5)}


`Labware`s have a minimum/maximum volume, so if you try to remove/add too much, you'll get an error:

In [7]:
plate.add(['A01', 'B01', 'C01'], [200, 200, 2000])

VolumeOverflowError: Too much volume for "24-well plate".C01: 300.0 + 2000 > 1000

### Troughs
Troughs are a little weird, because for the robot, they have multiple rows, even though it's actually just one big well.

To work with troughs, we can create `Labware` with `row=1, virtual_rows=8` that emulates a trough having enough space for 8 tips (`A01` through `H01`), but just one well:

In [ ]:
quadruple_trough = liquidhandling.Labware('4xTrough', 1, 4,
    min_volume=1000, max_volume=30*1000,
    virtual_rows=8,
    initial_volumes=[20*1000, 10*1000, 10*1000, 10*1000]
)
print(quadruple_trough)

We can access an entire column of well ids to aspirate 100 µl (per tip) from the trough, removing 400 µl in total:

In [ ]:
quadruple_trough.remove(['A01', 'B01', 'C01', 'D01'], 100)
print(quadruple_trough)