# Advanced Worklist Commands
`robotools` supports all features of the EVOware worklist file format.

For example, you can `decontaminate`, `wash`, `set_ditis`, or use `aspirate_well`/`dispense_well` to customize individual steps.

In [1]:
import numpy
import robotools

plate = robotools.Labware('96-well plate', 8, 12, min_volume=10, max_volume=250)

with robotools.Worklist() as wl:
    wl.comment("""
    We can add multiline-comments about our wash procedure:
    Washing scheme 3 (defined in the EVOware) is used.
    """)
    wl.wash(scheme=3)
    
    # pipetting system liquid into A01
    wl.aspirate_well(robotools.Labwares.SystemLiquid, position=1, volume=100, rack_type='System')
    wl.dispense(plate, 'A01', 100)
    
    wl.decontaminate()
    
    wl.dispense(
        plate, plate.wells[4:,:4],
        volumes=numpy.array([
            [30,40,50,60],
            [30,40,50,60],
            [30,40,50,60],
            [30,40,50,60],
        ])            
    )
    
    wl.comment('One-to-many transfer from A01 to A02-A04')
    wl.transfer(
        plate, 'A01',
        plate, ['A02', 'A03', 'A04'],
        volumes=10,
        liquid_class='MyAwesomeLiquidClass'
    )
    
    wl.comment('Using tips 2/3/4')
    wl.aspirate(plate, 'A01', volumes=10, tip=robotools.Tip.T2)
    wl.aspirate(plate, 'A01', volumes=10, tip=robotools.Tip.T3)
    wl.aspirate(plate, 'A01', volumes=10, tip=robotools.Tip.T4)
    wl.dispense(plate, 'B02', volumes=10, tip=2)
    wl.dispense(plate, 'C02', volumes=10, tip=3)
    wl.dispense(plate, 'D02', volumes=10, tip=4)
    
print(plate)
print(wl)

96-well plate
[[40. 10. 10. 10.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [30. 40. 50. 60.  0.  0.  0.  0.  0.  0.  0.  0.]
 [30. 40. 50. 60.  0.  0.  0.  0.  0.  0.  0.  0.]
 [30. 40. 50. 60.  0.  0.  0.  0.  0.  0.  0.  0.]
 [30. 40. 50. 60.  0.  0.  0.  0.  0.  0.  0.  0.]]
C;We can add multiline-comments about our wash procedure:
C;Washing scheme 3 (defined in the EVOware) is used.
W3;
A;Systemliquid;;System;1;;100.00;;;;
D;96-well plate;;;1;;100.00;;;;
WD;
D;96-well plate;;;5;;30.00;;;;
D;96-well plate;;;6;;30.00;;;;
D;96-well plate;;;7;;30.00;;;;
D;96-well plate;;;8;;30.00;;;;
D;96-well plate;;;13;;40.00;;;;
D;96-well plate;;;14;;40.00;;;;
D;96-well plate;;;15;;40.00;;;;
D;96-well plate;;;16;;40.00;;;;
D;96-well plate;;;21;;50.00;;;;
D;96-well plate;;;22;;50.00;;;;
D;96-well plate;;;23;;50.00;;;;
D;96-well plate;;;24;;50.00;;;;
D;96-well