# Advanced Worklist Commands
`robotools` supports all features of the EVOware worklist file format.

For example, you can `decontaminate`, `wash`, `set_ditis`, or use `aspirate_well`/`dispense_well` to customize individual steps.

In [1]:
import numpy
import robotools

plate = robotools.Labware('96-well plate', 8, 12, min_volume=10, max_volume=250)

with robotools.Worklist() as wl:
    wl.comment("""
    We can add multiline-comments about our wash procedure:
    Washing scheme 3 (defined in the EVOware) is used.
    """)
    wl.wash(scheme=3)
    
    # pipetting system liquid into A01
    wl.aspirate_well(robotools.Labwares.SystemLiquid, position=1, volume=100, rack_type='System')
    wl.dispense(plate, 'A01', 100)
    
    wl.decontaminate()
    
    wl.comment('One-to-many transfer from A01 to A02-A04')
    wl.transfer(
        plate, 'A01',
        plate, ['A02', 'A03', 'A04'],
        volumes=10,
        liquid_class='MyAwesomeLiquidClass'
    )
    
    wl.comment('Using tips 2/3/4')
    wl.transfer(plate, 'A01', plate, 'A02', volumes=10, tip=robotools.Tip.T2)
    wl.transfer(plate, 'A01', plate, 'A02', volumes=10, tip=3)
    wl.transfer(plate, 'A01', plate, 'A02', volumes=10, tip=4)
    
print(plate)
print(wl)

96-well plate
[[40. 40. 10. 10.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
C;We can add multiline-comments about our wash procedure:
C;Washing scheme 3 (defined in the EVOware) is used.
W3;
A;Systemliquid;;System;1;;100.00;;;;
D;96-well plate;;;1;;100.00;;;;
WD;
C;One-to-many transfer from A01 to A02-A04
A;96-well plate;;;1;;10.00;MyAwesomeLiquidClass;;;
D;96-well plate;;;9;;10.00;MyAwesomeLiquidClass;;;
W1;
A;96-well plate;;;1;;10.00;MyAwesomeLiquidClass;;;
D;96-well plate;;;17;;10.00;MyAwesomeLiquidClass;;;
W1;
A;96-well plate;;;1;;10.00;MyAwesomeLiquidClass;;;
D;96-well plate;;;25;;10.00;MyAwesomeLiquidClass;;;
W1;
C;Using tips 2/3/4
A;96-we