# Advanced Worklist Commands
This example shows how to craft fine-tuned worklists.

In [2]:
%load_ext autoreload
%autoreload 2

import numpy

from robotools import liquidhandling
from robotools import evotools

## Labwares
For this example, we use just one 96-well plate.

In [3]:
plate = liquidhandling.Labware('96-well plate', 8, 12, min_volume=10, max_volume=250)
print(plate)

96-well plate
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Pipetting the assay
Here, we're creating a GWL-worklist that can be given to the EVOware. It will prepare the 96-well assay plate with mastermix and transfer the samples.

The `Worklist` implements almost all commands of EVOware worklists. For example, you can `decontaminate`, `wash`, `set_ditis`, or use `aspirate_well`/`dispense_well` to customize individual steps.

In [5]:
with evotools.Worklist() as wl:
    wl.comment("""
    We can add multiline-comments about our wash procedure:
    Washing scheme 3 (defined in the EVOware) is used.
    """)
    wl.wash(scheme=3)
    
    # pipetting system liquid into A01
    wl.aspirate_well(evotools.Labwares.SystemLiquid, position=1, volume=100, rack_type='System')
    wl.dispense(plate, 'A01', 100)
    
    wl.decontaminate()
    
    wl.dispense(
        plate, plate.wells[4:,:4],
        volumes=numpy.array([
            [30,40,50,60],
            [30,40,50,60],
            [30,40,50,60],
            [30,40,50,60],
        ])            
    )
    
    wl.comment('One-to-many transfer from A01 to A02-A04')
    wl.transfer(
        plate, 'A01',
        plate, ['A02', 'A03', 'A04'],
        volumes=10,
        liquid_class='MyAwesomeLiquidClass'
    )
    
    wl.comment('Using tips 2/3/4')
    wl.aspirate(plate, 'A01', volumes=10, tip=evotools.Tip.T2)
    wl.aspirate(plate, 'A01', volumes=10, tip=evotools.Tip.T3)
    wl.aspirate(plate, 'A01', volumes=10, tip=evotools.Tip.T4)
    wl.dispense(plate, 'B02', volumes=10, tip=2)
    wl.dispense(plate, 'C02', volumes=10, tip=3)
    wl.dispense(plate, 'D02', volumes=10, tip=4)
    
print(plate)
print(wl)

96-well plate
[[ 80.  20.  20.  20.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  20.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  20.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  20.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 60.  80. 100. 120.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 60.  80. 100. 120.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 60.  80. 100. 120.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 60.  80. 100. 120.   0.   0.   0.   0.   0.   0.   0.   0.]]
C;We can add multiline-comments about our wash procedure:
C;Washing scheme 3 (defined in the EVOware) is used.
W3;
A;Systemliquid;;System;1;;100.00;;;;
D;96-well plate;;;1;;100.00;;;;
WD;
D;96-well plate;;;5;;30.00;;;;
D;96-well plate;;;6;;30.00;;;;
D;96-well plate;;;7;;30.00;;;;
D;96-well plate;;;8;;30.00;;;;
D;96-well plate;;;13;;40.00;;;;
D;96-well plate;;;14;;40.00;;;;
D;96-well plate;;;15;;40.00;;;;
D;96-well plate;;;16;;40.00;;;;
D;96-well plate;;;21;;50.00;;;;
D;96-well