# Dilution Series
This example shows how to use `liquidhandling.Labware` to plan a simple dilution series.

In [1]:
%load_ext autoreload
%autoreload 2

import numpy

from robotools import liquidhandling

## Defining Labwares
Let's assume we have 4 different stock solutions (`stocks`) that we want to dilute into a 96-well plate (`dilutions`):

In [2]:
# here we create a 1x4 trough that can be accessed with all 8 tips
stocks = liquidhandling.Labware('StockTrough', 1, 4,
    min_volume=1000, max_volume=30*1000,
    virtual_rows=8,
    initial_volumes=[20*1000, 10*1000, 10*1000, 10*1000]
)

# this will be the 96-well plate with dilutions
dilutions = liquidhandling.Labware('Dilutions', 8, 12, 10, 250)

print(stocks)
print(dilutions)

StockTrough
[[20000. 10000. 10000. 10000.]]
Dilutions
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Adding and removing volumes
In the first step, we aspirate 200 µl from the four stock solutions and dispense them to the 96-well plate:

In [3]:
stocks.remove(stocks.wells[1,:], 200, label='transfer to plate')
dilutions.add(dilutions.wells[0:4,0], 200, label='transfer from stocks')

The history of the `stocks` shows that we have removed 200 µl from each one.

In [4]:
print(stocks.report)

StockTrough
initial
[[20000. 10000. 10000. 10000.]]

transfer to plate
[[19800.  9800.  9800.  9800.]]



Accordingly, the history of the `dilutions` plate shows that we've added 200 µl into A01, B01, C01 and D01.

In [5]:
print(dilutions.report)

Dilutions
initial
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

transfer from stocks
[[200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]



## Dilutions
Now we can do 10x dilutions into the next colums.

In [6]:
dilutions.remove(dilutions.wells[0:4,0], 20, label='aspirating')
dilutions.add(dilutions.wells[0:4,1], 20, label='dispensing')
# fill up with water (trough not shown)
dilutions.add(dilutions.wells[0:4,1], 180, label='dilute 10x with water')
print(dilutions.report)

Dilutions
initial
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

transfer from stocks
[[200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]

aspirating
[[180.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [180.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [18

The history can be condensed to make it easier to read:

In [7]:
dilutions.condense_log(n=3)
print(dilutions.report)

Dilutions
initial
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

transfer from stocks
[[200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]

dilute 10x with water
[[180. 200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [180. 200.   0.   0.   0.   0.   0.   0.   0.   0.   0.

Of course, we can use a for-loop to do the next dilutions.

In [8]:
for c in [1,2,3]:
    dilutions.remove(dilutions.wells[0:4,c], 20, label='aspirating')
    dilutions.add(dilutions.wells[0:4,c+1], 20, label='dispensing')
    dilutions.add(dilutions.wells[0:4,c+1], 180, label='dilute 10x with water')
    dilutions.condense_log(3)
print(dilutions.report)

Dilutions
initial
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

transfer from stocks
[[200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]

dilute 10x with water
[[180. 200.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [180. 200.   0.   0.   0.   0.   0.   0.   0.   0.   0.

You might have guessed that the story doesn't end here.

The above example has shown how you can plan and debug pipetting steps _in silico_, but at this point you don't have a robot protocol yet.

Proceed to `Evotools_AssayPreparation` to learn how you can create GWL-worklists on the fly.